In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"C:\Users\samru\OneDrive\Desktop\SIH_2025\AI-Pollution-Forecast-and-Policy-Dashboard\ML\Raw\TROPOMI\tropomi_no2_hourly_2023_2025_real.csv")

In [5]:
df

,datetime,mean_concentration,data_source
0,2023-01-01 00:00:00,1.196896e+20,tropomi_observed_or_interpolated
1,2023-01-01 01:00:00,1.196896e+20,tropomi_observed_or_interpolated
2,2023-01-01 02:00:00,1.196896e+20,tropomi_observed_or_interpolated
3,2023-01-01 03:00:00,1.196896e+20,tropomi_observed_or_interpolated
4,2023-01-01 04:00:00,1.196896e+20,tropomi_observed_or_interpolated
...,...,...,...
26299,2025-12-31 19:00:00,8.564856e+19,extrapolated_from_last_2023_value
26300,2025-12-31 20:00:00,8.564856e+19,extrapolated_from_last_2023_value
26301,2025-12-31 21:00:00,8.564856e+19,extrapolated_from_last_2023_value
26302,2025-12-31 22:00:00,8.564856e+19,extrapolated_from_last_2023_value
26303,2025-12-31 23:00:00,8.564856e+19,extrapolated_from_last_2023_value

In [6]:
print(df.shape)
print(df.dtypes)
df.isnull().sum()

(26304, 3)
datetime               object
mean_concentration    float64
data_source            object
dtype: object

datetime              0
mean_concentration    0
data_source           0
dtype: int64

In [7]:
before = len(df)
df = df.drop_duplicates()
print("Duplicates removed:", before - len(df))

Duplicates removed: 0

In [8]:
df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')
df['datetime'].isnull().sum()   # check if any invalid timestamps

np.int64(0)

In [9]:
print("Missing values per column:")
df.isnull().sum()

Missing values per column:

datetime              0
mean_concentration    0
data_source           0
dtype: int64

In [10]:
mean_val = df['mean_concentration'].mean()
df['mean_concentration'].fillna(mean_val, inplace=True)
print("Filled missing mean_concentration with:", mean_val)

Filled missing mean_concentration with: 8.169711159166509e+19

C:\Users\samru\AppData\Local\Temp\ipykernel_1820\4147287552.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mean_concentration'].fillna(mean_val, inplace=True)

In [11]:
Q1 = df['mean_concentration'].quantile(0.25)
Q3 = df['mean_concentration'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower bound:", lower)
print("Upper bound:", upper)

outliers = df[(df['mean_concentration'] < lower) | (df['mean_concentration'] > upper)]
print("Total outliers found:", len(outliers))

Lower bound: 6.9813276030497866e+19
Upper bound: 9.514973146644298e+19
Total outliers found: 3192

In [12]:
df_no_outliers = df[(df['mean_concentration'] >= lower) & (df['mean_concentration'] <= upper)]
print("Shape after removing outliers:", df_no_outliers.shape)

Shape after removing outliers: (23112, 3)

In [13]:
df['mean_concentration'] = np.where(df['mean_concentration'] < lower, lower, df['mean_concentration'])
df['mean_concentration'] = np.where(df['mean_concentration'] > upper, upper, df['mean_concentration'])

print("Outliers capped.")

Outliers capped.

In [14]:
print(df.isnull().sum())
df.describe()

datetime              0
mean_concentration    0
data_source           0
dtype: int64

                  datetime  mean_concentration
count                26304        2.630400e+04
mean   2024-07-01 23:30:00        8.231860e+19
min    2023-01-01 00:00:00        6.981328e+19
25%    2023-10-01 23:45:00        7.931445e+19
50%    2024-07-01 23:30:00        8.564856e+19
75%    2025-04-01 23:15:00        8.564856e+19
max    2025-12-31 23:00:00        9.514973e+19
std                    NaN        6.081089e+18

In [15]:
df

,datetime,mean_concentration,data_source
0,2023-01-01 00:00:00,9.514973e+19,tropomi_observed_or_interpolated
1,2023-01-01 01:00:00,9.514973e+19,tropomi_observed_or_interpolated
2,2023-01-01 02:00:00,9.514973e+19,tropomi_observed_or_interpolated
3,2023-01-01 03:00:00,9.514973e+19,tropomi_observed_or_interpolated
4,2023-01-01 04:00:00,9.514973e+19,tropomi_observed_or_interpolated
...,...,...,...
26299,2025-12-31 19:00:00,8.564856e+19,extrapolated_from_last_2023_value
26300,2025-12-31 20:00:00,8.564856e+19,extrapolated_from_last_2023_value
26301,2025-12-31 21:00:00,8.564856e+19,extrapolated_from_last_2023_value
26302,2025-12-31 22:00:00,8.564856e+19,extrapolated_from_last_2023_value
26303,2025-12-31 23:00:00,8.564856e+19,extrapolated_from_last_2023_value