In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\samru\OneDrive\Desktop\SIH_2025\AI-Pollution-Forecast-and-Policy-Dashboard\ML\Raw\Air_Quality_Data\AQI_daily_2023_Alipur_Delhi_DPCC_2023.xlsx")

In [3]:
df.head()

,Day,January,February,March,April,May,June,July,August,September,October,November,December
0,1,292.0,132.0,134.0,201.0,78.0,75.0,65.0,111.0,139.0,146.0,320.0,341.0
1,2,NaN,171.0,223.0,112.0,61.0,91.0,60.0,79.0,131.0,143.0,360.0,341.0
2,3,369.0,203.0,123.0,163.0,95.0,96.0,94.0,69.0,140.0,160.0,425.0,308.0
3,4,300.0,266.0,113.0,86.0,150.0,NaN,155.0,81.0,134.0,166.0,383.0,316.0
4,5,307.0,253.0,116.0,124.0,171.0,NaN,98.0,65.0,90.0,180.0,401.0,306.0

In [4]:
df

,Day,January,February,March,April,May,June,July,August,September,October,November,December
0,1,292.0,132.0,134.0,201.0,78.0,75.0,65.0,111.0,139.0,146.0,320.0,341.0
1,2,NaN,171.0,223.0,112.0,61.0,91.0,60.0,79.0,131.0,143.0,360.0,341.0
2,3,369.0,203.0,123.0,163.0,95.0,96.0,94.0,69.0,140.0,160.0,425.0,308.0
3,4,300.0,266.0,113.0,86.0,150.0,NaN,155.0,81.0,134.0,166.0,383.0,316.0
4,5,307.0,253.0,116.0,124.0,171.0,NaN,98.0,65.0,90.0,180.0,401.0,306.0
5,6,360.0,298.0,128.0,156.0,220.0,NaN,57.0,95.0,96.0,178.0,358.0,293.0
6,7,334.0,297.0,186.0,142.0,200.0,207.0,70.0,96.0,173.0,221.0,304.0,338.0
7,8,326.0,119.0,211.0,153.0,123.0,145.0,60.0,112.0,72.0,176.0,352.0,370.0
8,9,366.0,211.0,93.0,230.0,203.0,163.0,NaN,122.0,59.0,192.0,433.0,331.0
9,10,357.0,277.0,174.0,223.0,210.0,137.0,NaN,131.0,61.0,NaN,283.0,323.0
10,11,261.0,289.0,225.0,296.0,303.0,125.0,50.0,126.0,61.0,172.0,176.0,316.0
11,12,369.0,161.0,NaN,220.0,248.0,154.0,55.0,120.0,61.0,221.0,176.0,363.0
12,13,378.0,125.0,257.0,220.0,263.0,201.0,91.0,103.0,81.0,247.0,358.0,399.0
13,14,345.0,116.0,266.0,300.0,252.0,226.0,NaN,105.0,100.0,246.0,394.0,354.0
14,15,204.0,175.0,228.0,308.0,171.0,162.0,NaN,100.0,76.0,196.0,399.0,339.0
15,16,276.0,277.0,280.0,205.0,279.0,119.0,NaN,98.0,65.0,155.0,437.0,370.0
16,17,260.0,381.0,167.0,NaN,345.0,140.0,NaN,126.0,60.0,59.0,371.0,330.0
17,18,282.0,381.0,169.0,314.0,123.0,84.0,NaN,145.0,61.0,91.0,333.0,332.0
18,19,324.0,321.0,NaN,252.0,174.0,70.0,NaN,99.0,88.0,100.0,368.0,294.0
19,20,197.0,359.0,157.0,158.0,188.0,76.0,NaN,NaN,109.0,188.0,363.0,305.0
20,21,310.0,286.0,55.0,139.0,296.0,88.0,NaN,NaN,103.0,197.0,393.0,379.0
21,22,404.0,313.0,120.0,140.0,212.0,108.0,68.0,80.0,106.0,273.0,423.0,420.0
22,23,343.0,223.0,186.0,135.0,224.0,122.0,65.0,64.0,101.0,229.0,420.0,454.0
23,24,246.0,157.0,219.0,170.0,NaN,171.0,65.0,69.0,103.0,209.0,442.0,404.0
24,25,162.0,231.0,73.0,212.0,NaN,64.0,NaN,109.0,103.0,218.0,NaN,361.0
25,26,304.0,295.0,115.0,276.0,NaN,64.0,66.0,149.0,114.0,218.0,394.0,364.0
26,27,215.0,270.0,130.0,261.0,123.0,65.0,64.0,185.0,130.0,236.0,415.0,351.0
27,28,230.0,236.0,160.0,168.0,170.0,76.0,66.0,NaN,127.0,301.0,333.0,319.0
28,29,343.0,NaN,187.0,259.0,139.0,83.0,NaN,144.0,152.0,303.0,277.0,324.0
29,30,NaN,NaN,179.0,127.0,180.0,50.0,91.0,NaN,159.0,311.0,391.0,367.0
30,31,138.0,NaN,61.0,NaN,74.0,NaN,81.0,80.0,NaN,313.0,NaN,318.0
31,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Good,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN
33,Satisfactory,NaN,NaN,4.0,1.0,4.0,12.0,17.0,13.0,14.0,3.0,NaN,NaN
34,Moderate,3.0,8.0,17.0,13.0,12.0,11.0,1.0,14.0,16.0,13.0,2.0,NaN
35,Poor,10.0,15.0,8.0,13.0,10.0,3.0,NaN,NaN,NaN,10.0,2.0,2.0
36,Very poor,15.0,5.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,4.0,17.0,26.0
37,Severe,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,3.0
38,NaN,2.0,NaN,2.0,1.0,3.0,3.0,12.0,4.0,NaN,1.0,1.0,NaN
39,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,% of Availability,93.0,100.0,93.0,96.0,90.0,90.0,61.0,87.0,100.0,96.0,96.0,100.0

In [ ]:
print("Missing values per column:")
print(df.isna().sum())

Missing values per column:
Day          1
January      0
February     0
March        0
April        0
May          0
June         0
July         0
August       0
September    0
October      0
November     0
December     0
dtype: int64

In [7]:
# Count duplicates first
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
df = df.drop_duplicates(keep="first").reset_index(drop=True)
print("Duplicates removed.")

Number of duplicate rows: 0
Duplicates removed.

In [8]:
import numpy as np

df_out = df.copy()

for col in month_cols:
    Q1 = df_out[col].quantile(0.25)
    Q3 = df_out[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    median_val = df_out[col].median()

    # Replace outliers
    df_out[col] = np.where((df_out[col] < lower) | (df_out[col] > upper),
                           median_val,
                           df_out[col])

print("Outliers replaced using month-wise median.")

Outliers replaced using month-wise median.

In [11]:
df

,Day,January,February,March,April,May,June,July,August,September,October,November,December
0,1,292.000000,132.00000,134.000000,201.000000,78.000000,75.000000,65.000000,111.00000,139.000000,146.000000,320.000000,341.000000
1,2,249.314286,171.00000,223.000000,112.000000,61.000000,91.000000,60.000000,79.00000,131.000000,143.000000,360.000000,341.000000
2,3,369.000000,203.00000,123.000000,163.000000,95.000000,96.000000,94.000000,69.00000,140.000000,160.000000,425.000000,308.000000
3,4,300.000000,266.00000,113.000000,86.000000,150.000000,99.454545,155.000000,81.00000,134.000000,166.000000,383.000000,316.000000
4,5,307.000000,253.00000,116.000000,124.000000,171.000000,99.454545,98.000000,65.00000,90.000000,180.000000,401.000000,306.000000
5,6,360.000000,298.00000,128.000000,156.000000,220.000000,99.454545,57.000000,95.00000,96.000000,178.000000,358.000000,293.000000
6,7,334.000000,297.00000,186.000000,142.000000,200.000000,207.000000,70.000000,96.00000,173.000000,221.000000,304.000000,338.000000
7,8,326.000000,119.00000,211.000000,153.000000,123.000000,145.000000,60.000000,112.00000,72.000000,176.000000,352.000000,370.000000
8,9,366.000000,211.00000,93.000000,230.000000,203.000000,163.000000,63.041667,122.00000,59.000000,192.000000,433.000000,331.000000
9,10,357.000000,277.00000,174.000000,223.000000,210.000000,137.000000,63.041667,131.00000,61.000000,171.444444,283.000000,323.000000
10,11,261.000000,289.00000,225.000000,296.000000,303.000000,125.000000,50.000000,126.00000,61.000000,172.000000,176.000000,316.000000
11,12,369.000000,161.00000,142.911765,220.000000,248.000000,154.000000,55.000000,120.00000,61.000000,221.000000,176.000000,363.000000
12,13,378.000000,125.00000,257.000000,220.000000,263.000000,201.000000,91.000000,103.00000,81.000000,247.000000,358.000000,399.000000
13,14,345.000000,116.00000,266.000000,300.000000,252.000000,226.000000,63.041667,105.00000,100.000000,246.000000,394.000000,354.000000
14,15,204.000000,175.00000,228.000000,308.000000,171.000000,162.000000,63.041667,100.00000,76.000000,196.000000,399.000000,339.000000
15,16,276.000000,277.00000,280.000000,205.000000,279.000000,119.000000,63.041667,98.00000,65.000000,155.000000,437.000000,370.000000
16,17,260.000000,381.00000,167.000000,167.885714,345.000000,140.000000,63.041667,126.00000,60.000000,59.000000,371.000000,330.000000
17,18,282.000000,381.00000,169.000000,314.000000,123.000000,84.000000,63.041667,145.00000,61.000000,91.000000,333.000000,332.000000
18,19,324.000000,321.00000,142.911765,252.000000,174.000000,70.000000,63.041667,99.00000,88.000000,100.000000,368.000000,294.000000
19,20,197.000000,359.00000,157.000000,158.000000,188.000000,76.000000,63.041667,96.16129,109.000000,188.000000,363.000000,305.000000
20,21,310.000000,286.00000,55.000000,139.000000,296.000000,88.000000,63.041667,96.16129,103.000000,197.000000,393.000000,379.000000
21,22,404.000000,313.00000,120.000000,140.000000,212.000000,108.000000,68.000000,80.00000,106.000000,273.000000,423.000000,420.000000
22,23,343.000000,223.00000,186.000000,135.000000,224.000000,122.000000,65.000000,64.00000,101.000000,229.000000,420.000000,454.000000
23,24,246.000000,157.00000,219.000000,170.000000,158.705882,171.000000,65.000000,69.00000,103.000000,209.000000,442.000000,404.000000
24,25,162.000000,231.00000,73.000000,212.000000,158.705882,64.000000,63.041667,109.00000,103.000000,218.000000,303.085714,361.000000
25,26,304.000000,295.00000,115.000000,276.000000,158.705882,64.000000,66.000000,149.00000,114.000000,218.000000,394.000000,364.000000
26,27,215.000000,270.00000,130.000000,261.000000,123.000000,65.000000,64.000000,185.00000,130.000000,236.000000,415.000000,351.000000
27,28,230.000000,236.00000,160.000000,168.000000,170.000000,76.000000,66.000000,96.16129,127.000000,301.000000,333.000000,319.000000
28,29,343.000000,217.21875,187.000000,259.000000,139.000000,83.000000,63.041667,144.00000,152.000000,303.000000,277.000000,324.000000
29,30,249.314286,217.21875,179.000000,127.000000,180.000000,50.000000,91.000000,96.16129,159.000000,311.000000,391.000000,367.000000
30,31,138.000000,217.21875,61.000000,167.885714,74.000000,99.454545,81.000000,80.00000,96.515152,313.000000,303.085714,318.000000
31,,249.314286,217.21875,142.911765,167.885714,158.705882,99.454545,63.041667,96.16129,96.515152,171.444444,303.085714,310.314286
32,Good,249.314286,217.21875,142.911765,167.885714,158.705882,1.000000,1.000000,96.16129,96.515152,171.444444,303.085714,310.314286
33,Satisfactory,249.314286,217.21875,4.000000,1.000000,4.000000,12.000000,17.000000,13.00000,14.000000,3.000000,303.085714,310.314286
34,Moderate,3.000000,8.00000,17.000000,13.000000,12.000000,11.000000,1.000000,14.00000,16.000000,13.000000,2.000000,310.314286
35,Poor,10.000000,15.00000,8.000000,13.000000,10.000000,3.000000,63.041667,96.16129,96.515152,10.000000,2.000000,2.000000
36,Very poor,15.000000,5.00000,142.911765,2.000000,2.000000,99.454545,63.041667,96.16129,96.515152,4.000000,17.000000,26.000000
37,Severe,1.000000,217.21875,142.911765,167.885714,158.705882,99.454545,63.041667,96.16129,96.515152,171.444444,8.000000,3.000000
38,NaN,2.000000,217.21875,2.000000,1.000000,3.000000,3.000000,12.000000,4.00000,96.515152,1.000000,1.000000,310.314286
39,SP,249.314286,217.21875,142.911765,167.885714,158.705882,99.454545,63.041667,96.16129,96.515152,171.444444,303.085714,310.314286
40,% of Availability,93.000000,100.00000,93.000000,96.000000,90.000000,90.000000,61.000000,87.00000,100.000000,96.000000,96.000000,100.000000