In [1]:
import pandas as pd

In [3]:
df=pd.read_excel(r"C:\Users\samru\OneDrive\Desktop\SIH_2025\AI-Pollution-Forecast-and-Policy-Dashboard\ML\Raw\Air_Quality_Data\AQI_daily_2023_Anand_Vihar_Delhi_DPCC_2023.xlsx")

In [4]:
df

,Day,January,February,March,April,May,June,July,August,September,October,November,December
0,1,294.0,216.0,232.0,121.0,112.0,155.0,175.0,254.0,340.0,165.0,416.0,400.0
1,2,375.0,298.0,289.0,188.0,103.0,135.0,170.0,252.0,NaN,153.0,449.0,359.0
2,3,400.0,346.0,198.0,278.0,117.0,158.0,254.0,NaN,270.0,176.0,NaN,363.0
3,4,390.0,415.0,194.0,NaN,151.0,211.0,227.0,215.0,253.0,177.0,473.0,313.0
4,5,422.0,323.0,225.0,161.0,223.0,185.0,209.0,NaN,150.0,201.0,NaN,317.0
5,6,448.0,366.0,140.0,161.0,310.0,NaN,203.0,167.0,122.0,223.0,438.0,303.0
6,7,434.0,387.0,236.0,127.0,260.0,211.0,NaN,194.0,129.0,270.0,447.0,373.0
7,8,435.0,304.0,278.0,167.0,143.0,159.0,211.0,NaN,111.0,176.0,449.0,345.0
8,9,471.0,332.0,150.0,273.0,253.0,181.0,NaN,NaN,61.0,210.0,450.0,321.0
9,10,445.0,182.0,220.0,267.0,212.0,157.0,NaN,NaN,92.0,NaN,NaN,308.0
10,11,379.0,356.0,248.0,291.0,341.0,153.0,138.0,NaN,79.0,203.0,288.0,316.0
11,12,382.0,274.0,313.0,215.0,316.0,NaN,119.0,NaN,140.0,243.0,286.0,395.0
12,13,375.0,212.0,304.0,233.0,249.0,213.0,118.0,NaN,117.0,286.0,382.0,417.0
13,14,370.0,187.0,253.0,263.0,316.0,225.0,NaN,NaN,121.0,261.0,445.0,318.0
14,15,266.0,227.0,321.0,246.0,150.0,NaN,NaN,NaN,106.0,335.0,427.0,332.0
15,16,368.0,310.0,326.0,317.0,285.0,144.0,NaN,NaN,96.0,284.0,433.0,398.0
16,17,348.0,415.0,254.0,288.0,350.0,176.0,NaN,331.0,54.0,NaN,406.0,372.0
17,18,365.0,388.0,154.0,311.0,174.0,119.0,NaN,322.0,51.0,NaN,315.0,356.0
18,19,390.0,355.0,218.0,259.0,171.0,NaN,NaN,225.0,76.0,NaN,351.0,305.0
19,20,275.0,357.0,308.0,152.0,195.0,145.0,NaN,168.0,147.0,244.0,374.0,311.0
20,21,312.0,250.0,114.0,118.0,323.0,104.0,NaN,127.0,187.0,273.0,371.0,389.0
21,22,427.0,345.0,216.0,159.0,248.0,NaN,NaN,261.0,177.0,NaN,377.0,449.0
22,23,372.0,242.0,242.0,153.0,256.0,181.0,96.0,85.0,99.0,NaN,396.0,469.0
23,24,235.0,190.0,292.0,214.0,117.0,159.0,88.0,120.0,200.0,252.0,438.0,441.0
24,25,180.0,263.0,101.0,126.0,158.0,98.0,NaN,NaN,146.0,NaN,NaN,396.0
25,26,337.0,353.0,215.0,248.0,173.0,97.0,99.0,400.0,214.0,311.0,438.0,396.0
26,27,278.0,303.0,163.0,243.0,159.0,125.0,115.0,NaN,178.0,329.0,387.0,460.0
27,28,278.0,238.0,161.0,187.0,219.0,115.0,NaN,NaN,161.0,355.0,335.0,424.0
28,29,378.0,NaN,248.0,228.0,176.0,189.0,NaN,385.0,174.0,NaN,349.0,442.0
29,30,232.0,NaN,244.0,131.0,167.0,184.0,102.0,356.0,197.0,385.0,414.0,438.0
30,31,246.0,NaN,122.0,NaN,153.0,NaN,206.0,347.0,NaN,422.0,NaN,408.0
31,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Satisfactory,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,8.0,NaN,NaN,NaN
34,Moderate,1.0,3.0,10.0,13.0,16.0,19.0,7.0,5.0,17.0,5.0,NaN,NaN
35,Poor,8.0,9.0,16.0,14.0,9.0,4.0,6.0,5.0,3.0,12.0,2.0,NaN
36,Very poor,15.0,14.0,5.0,2.0,6.0,NaN,NaN,6.0,1.0,5.0,10.0,22.0
37,Severe,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,14.0,9.0
38,NaN,NaN,NaN,NaN,1.0,NaN,5.0,15.0,14.0,1.0,8.0,4.0,NaN
39,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,% of Availability,100.0,100.0,100.0,96.0,100.0,83.0,51.0,54.0,96.0,74.0,86.0,100.0

In [5]:
df.isnull().sum()

Day           1
January       5
February      8
March         6
April         7
May           6
June         11
July         20
August       18
September     6
October      12
November     10
December      7
dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=['number']).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
print(df)

                  Day     January    February       March       April  \
0                   1  294.000000  216.000000  232.000000  121.000000
1                   2  375.000000  298.000000  289.000000  188.000000
2                   3  400.000000  346.000000  198.000000  278.000000
3                   4  390.000000  415.000000  194.000000  183.852941
4                   5  422.000000  323.000000  225.000000  161.000000
5                   6  448.000000  366.000000  140.000000  161.000000
6                   7  434.000000  387.000000  236.000000  127.000000
7                   8  435.000000  304.000000  278.000000  167.000000
8                   9  471.000000  332.000000  150.000000  273.000000
9                  10  445.000000  182.000000  220.000000  267.000000
10                 11  379.000000  356.000000  248.000000  291.000000
11                 12  382.000000  274.000000  313.000000  215.000000
12                 13  375.000000  212.000000  304.000000  233.000000
13                 14  370.000000  187.000000  253.000000  263.000000
14                 15  266.000000  227.000000  321.000000  246.000000
15                 16  368.000000  310.000000  326.000000  317.000000
16                 17  348.000000  415.000000  254.000000  288.000000
17                 18  365.000000  388.000000  154.000000  311.000000
18                 19  390.000000  355.000000  218.000000  259.000000
19                 20  275.000000  357.000000  308.000000  152.000000
20                 21  312.000000  250.000000  114.000000  118.000000
21                 22  427.000000  345.000000  216.000000  159.000000
22                 23  372.000000  242.000000  242.000000  153.000000
23                 24  235.000000  190.000000  292.000000  214.000000
24                 25  180.000000  263.000000  101.000000  126.000000
25                 26  337.000000  353.000000  215.000000  248.000000
26                 27  278.000000  303.000000  163.000000  243.000000
27                 28  278.000000  238.000000  161.000000  187.000000
28                 29  378.000000  259.454545  248.000000  228.000000
29                 30  232.000000  259.454545  244.000000  131.000000
30                 31  246.000000  259.454545  122.000000  183.852941
31                     306.611111  259.454545  203.142857  183.852941
32               Good  306.611111  259.454545  203.142857  183.852941
33       Satisfactory  306.611111  259.454545  203.142857  183.852941
34           Moderate    1.000000    3.000000   10.000000   13.000000
35               Poor    8.000000    9.000000   16.000000   14.000000
36          Very poor   15.000000   14.000000    5.000000    2.000000
37             Severe    7.000000    2.000000  203.142857  183.852941
38                NaN  306.611111  259.454545  203.142857    1.000000
39                 SP  306.611111  259.454545  203.142857  183.852941
40  % of Availability  100.000000  100.000000  100.000000   96.000000

           May   June        July      August   September     October  \
0   112.000000  155.0  175.000000  254.000000  340.000000  165.000000
1   103.000000  135.0  170.000000  252.000000  124.971429  153.000000
2   117.000000  158.0  254.000000  186.695652  270.000000  176.000000
3   151.000000  211.0  227.000000  215.000000  253.000000  177.000000
4   223.000000  185.0  209.000000  186.695652  150.000000  201.000000
5   310.000000  136.4  203.000000  167.000000  122.000000  223.000000
6   260.000000  211.0  124.380952  194.000000  129.000000  270.000000
7   143.000000  159.0  211.000000  186.695652  111.000000  176.000000
8   253.000000  181.0  124.380952  186.695652   61.000000  210.000000
9   212.000000  157.0  124.380952  186.695652   92.000000  208.241379
10  341.000000  153.0  138.000000  186.695652   79.000000  203.000000
11  316.000000  136.4  119.000000  186.695652  140.000000  243.000000
12  249.000000  213.0  118.000000  186.695652  117.000000  286.000000
13  316.000000  225.0  124.380952  186.695652  121.000000  261.000000
14  150.000000  136.4  124.380952  186.695652  106.000000  335.000000
15  285.000000  144.0  124.380952  186.695652   96.000000  284.000000
16  350.000000  176.0  124.380952  331.000000   54.000000  208.241379
17  174.000000  119.0  124.380952  322.000000   51.000000  208.241379
18  171.000000  136.4  124.380952  225.000000   76.000000  208.241379
19  195.000000  145.0  124.380952  168.000000  147.000000  244.000000
20  323.000000  104.0  124.380952  127.000000  187.000000  273.000000
21  248.000000  136.4  124.380952  261.000000  177.000000  208.241379
22  256.000000  181.0   96.000000   85.000000   99.000000  208.241379
23  117.000000  159.0   88.000000  120.000000  200.000000  252.000000
24  158.000000   98.0  124.380952  186.695652  146.000000  208.241379
25  173.000000   97.0   99.000000  400.000000  214.000000  311.000000
26  159.000000  125.0  115.000000  186.695652  178.000000  329.000000
27  219.000000  115.0  124.380952  186.695652  161.000000  355.000000
28  176.000000  189.0  124.380952  385.000000  174.000000  208.241379
29  167.000000  184.0  102.000000  356.000000  197.000000  385.000000
30  153.000000  136.4  206.000000  347.000000  124.971429  422.000000
31  191.742857  136.4  124.380952  186.695652  124.971429  208.241379
32  191.742857  136.4  124.380952  186.695652  124.971429  208.241379
33  191.742857    2.0    3.000000    1.000000    8.000000  208.241379
34   16.000000   19.0    7.000000    5.000000   17.000000    5.000000
35    9.000000    4.0    6.000000    5.000000    3.000000   12.000000
36    6.000000  136.4  124.380952    6.000000    1.000000    5.000000
37  191.742857  136.4  124.380952  186.695652  124.971429    1.000000
38  191.742857    5.0   15.000000   14.000000    1.000000    8.000000
39  191.742857  136.4  124.380952  186.695652  124.971429  208.241379
40  100.000000   83.0   51.000000   54.000000   96.000000   74.000000

      November    December
0   416.000000  400.000000
1   449.000000  359.000000
2   337.096774  363.000000
3   473.000000  313.000000
4   337.096774  317.000000
5   438.000000  303.000000
6   447.000000  373.000000
7   449.000000  345.000000
8   450.000000  321.000000
9   337.096774  308.000000
10  288.000000  316.000000
11  286.000000  395.000000
12  382.000000  417.000000
13  445.000000  318.000000
14  427.000000  332.000000
15  433.000000  398.000000
16  406.000000  372.000000
17  315.000000  356.000000
18  351.000000  305.000000
19  374.000000  311.000000
20  371.000000  389.000000
21  377.000000  449.000000
22  396.000000  469.000000
23  438.000000  441.000000
24  337.096774  396.000000
25  438.000000  396.000000
26  387.000000  460.000000
27  335.000000  424.000000
28  349.000000  442.000000
29  414.000000  438.000000
30  337.096774  408.000000
31  337.096774  346.029412
32  337.096774  346.029412
33  337.096774  346.029412
34  337.096774  346.029412
35    2.000000  346.029412
36   10.000000   22.000000
37   14.000000    9.000000
38    4.000000  346.029412
39  337.096774  346.029412
40   86.000000  100.000000

In [7]:
# Count duplicates first
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
df = df.drop_duplicates(keep="first").reset_index(drop=True)
print("Duplicates removed.")

Number of duplicate rows: 0
Duplicates removed.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Day        40 non-null     object
 1   January    41 non-null     float64
 2   February   41 non-null     float64
 3   March      41 non-null     float64
 4   April      41 non-null     float64
 5   May        41 non-null     float64
 6   June       41 non-null     float64
 7   July       41 non-null     float64
 8   August     41 non-null     float64
 9   September  41 non-null     float64
 10  October    41 non-null     float64
 11  November   41 non-null     float64
 12  December   41 non-null     float64
dtypes: float64(12), object(1)
memory usage: 4.3+ KB

In [15]:
def remove_outliers_iqr(df):
    df_clean = df.copy()
    numeric_cols = df_clean.select_dtypes(include=[np.number]).columns

    for col in numeric_cols:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]

    return df_clean
df_iqr_clean = remove_outliers_iqr(df)
print("Original shape:", df.shape)
print("After IQR:", df_iqr_clean.shape)

Original shape: (41, 13)
After IQR: (13, 13)

In [18]:
df

,Day,January,February,March,April,May,June,July,August,September,October,November,December
0,1,294.000000,216.000000,232.000000,121.000000,112.000000,155.0,175.000000,254.000000,340.000000,165.000000,416.000000,400.000000
1,2,375.000000,298.000000,289.000000,188.000000,103.000000,135.0,170.000000,252.000000,124.971429,153.000000,449.000000,359.000000
2,3,400.000000,346.000000,198.000000,278.000000,117.000000,158.0,254.000000,186.695652,270.000000,176.000000,337.096774,363.000000
3,4,390.000000,415.000000,194.000000,183.852941,151.000000,211.0,227.000000,215.000000,253.000000,177.000000,473.000000,313.000000
4,5,422.000000,323.000000,225.000000,161.000000,223.000000,185.0,209.000000,186.695652,150.000000,201.000000,337.096774,317.000000
5,6,448.000000,366.000000,140.000000,161.000000,310.000000,136.4,203.000000,167.000000,122.000000,223.000000,438.000000,303.000000
6,7,434.000000,387.000000,236.000000,127.000000,260.000000,211.0,124.380952,194.000000,129.000000,270.000000,447.000000,373.000000
7,8,435.000000,304.000000,278.000000,167.000000,143.000000,159.0,211.000000,186.695652,111.000000,176.000000,449.000000,345.000000
8,9,471.000000,332.000000,150.000000,273.000000,253.000000,181.0,124.380952,186.695652,61.000000,210.000000,450.000000,321.000000
9,10,445.000000,182.000000,220.000000,267.000000,212.000000,157.0,124.380952,186.695652,92.000000,208.241379,337.096774,308.000000
10,11,379.000000,356.000000,248.000000,291.000000,341.000000,153.0,138.000000,186.695652,79.000000,203.000000,288.000000,316.000000
11,12,382.000000,274.000000,313.000000,215.000000,316.000000,136.4,119.000000,186.695652,140.000000,243.000000,286.000000,395.000000
12,13,375.000000,212.000000,304.000000,233.000000,249.000000,213.0,118.000000,186.695652,117.000000,286.000000,382.000000,417.000000
13,14,370.000000,187.000000,253.000000,263.000000,316.000000,225.0,124.380952,186.695652,121.000000,261.000000,445.000000,318.000000
14,15,266.000000,227.000000,321.000000,246.000000,150.000000,136.4,124.380952,186.695652,106.000000,335.000000,427.000000,332.000000
15,16,368.000000,310.000000,326.000000,317.000000,285.000000,144.0,124.380952,186.695652,96.000000,284.000000,433.000000,398.000000
16,17,348.000000,415.000000,254.000000,288.000000,350.000000,176.0,124.380952,331.000000,54.000000,208.241379,406.000000,372.000000
17,18,365.000000,388.000000,154.000000,311.000000,174.000000,119.0,124.380952,322.000000,51.000000,208.241379,315.000000,356.000000
18,19,390.000000,355.000000,218.000000,259.000000,171.000000,136.4,124.380952,225.000000,76.000000,208.241379,351.000000,305.000000
19,20,275.000000,357.000000,308.000000,152.000000,195.000000,145.0,124.380952,168.000000,147.000000,244.000000,374.000000,311.000000
20,21,312.000000,250.000000,114.000000,118.000000,323.000000,104.0,124.380952,127.000000,187.000000,273.000000,371.000000,389.000000
21,22,427.000000,345.000000,216.000000,159.000000,248.000000,136.4,124.380952,261.000000,177.000000,208.241379,377.000000,449.000000
22,23,372.000000,242.000000,242.000000,153.000000,256.000000,181.0,96.000000,85.000000,99.000000,208.241379,396.000000,469.000000
23,24,235.000000,190.000000,292.000000,214.000000,117.000000,159.0,88.000000,120.000000,200.000000,252.000000,438.000000,441.000000
24,25,180.000000,263.000000,101.000000,126.000000,158.000000,98.0,124.380952,186.695652,146.000000,208.241379,337.096774,396.000000
25,26,337.000000,353.000000,215.000000,248.000000,173.000000,97.0,99.000000,400.000000,214.000000,311.000000,438.000000,396.000000
26,27,278.000000,303.000000,163.000000,243.000000,159.000000,125.0,115.000000,186.695652,178.000000,329.000000,387.000000,460.000000
27,28,278.000000,238.000000,161.000000,187.000000,219.000000,115.0,124.380952,186.695652,161.000000,355.000000,335.000000,424.000000
28,29,378.000000,259.454545,248.000000,228.000000,176.000000,189.0,124.380952,385.000000,174.000000,208.241379,349.000000,442.000000
29,30,232.000000,259.454545,244.000000,131.000000,167.000000,184.0,102.000000,356.000000,197.000000,385.000000,414.000000,438.000000
30,31,246.000000,259.454545,122.000000,183.852941,153.000000,136.4,206.000000,347.000000,124.971429,422.000000,337.096774,408.000000
31,,306.611111,259.454545,203.142857,183.852941,191.742857,136.4,124.380952,186.695652,124.971429,208.241379,337.096774,346.029412
32,Good,306.611111,259.454545,203.142857,183.852941,191.742857,136.4,124.380952,186.695652,124.971429,208.241379,337.096774,346.029412
33,Satisfactory,306.611111,259.454545,203.142857,183.852941,191.742857,2.0,3.000000,1.000000,8.000000,208.241379,337.096774,346.029412
34,Moderate,1.000000,3.000000,10.000000,13.000000,16.000000,19.0,7.000000,5.000000,17.000000,5.000000,337.096774,346.029412
35,Poor,8.000000,9.000000,16.000000,14.000000,9.000000,4.0,6.000000,5.000000,3.000000,12.000000,2.000000,346.029412
36,Very poor,15.000000,14.000000,5.000000,2.000000,6.000000,136.4,124.380952,6.000000,1.000000,5.000000,10.000000,22.000000
37,Severe,7.000000,2.000000,203.142857,183.852941,191.742857,136.4,124.380952,186.695652,124.971429,1.000000,14.000000,9.000000
38,NaN,306.611111,259.454545,203.142857,1.000000,191.742857,5.0,15.000000,14.000000,1.000000,8.000000,4.000000,346.029412
39,SP,306.611111,259.454545,203.142857,183.852941,191.742857,136.4,124.380952,186.695652,124.971429,208.241379,337.096774,346.029412
40,% of Availability,100.000000,100.000000,100.000000,96.000000,100.000000,83.0,51.000000,54.000000,96.000000,74.000000,86.000000,100.000000